/*-------------------------------------------------------------------------*
 |                                                                         
 |            STATA SUPPLEMENTAL SYNTAX FILE FOR ICPSR 36128
 |                         CENSUS OF JAILS, 2013
 |
 |
 | This Stata missing value recode program is provided for optional use with
 | the Stata system version of this data file as distributed by ICPSR.
 | The program replaces user-defined numeric missing values (e.g., -9)
 | with generic system missing "."  Note that Stata allows you to specify
 | up to 27 unique missing value codes.  Only variables with user-defined
 | missing values are included in this program.
 |
 | To apply the missing value recodes, users need to first open the
 | Stata data file on their system, apply the missing value recodes if
 | desired, then save a new copy of the data file with the missing values
 | applied.  Users are strongly advised to use a different filename when
 | saving the new file.
 |
 *------------------------------------------------------------------------*/

replace WEEK_FLAG = . if (WEEK_FLAG == -1)
replace WEEKN = . if (WEEKN == -1)
replace NONCITZ = . if (NONCITZ == -1)
replace NONCITZ_FLAG = . if (NONCITZ_FLAG == -1)
replace CONV = . if (CONV == -1)
replace CONVUNSENT = . if (CONVUNSENT == -1)
replace CONVUNSENT_FLAG = . if (CONVUNSENT_FLAG == -1)
replace CONVSENT = . if (CONVSENT == -1)
replace CONVSENT_FLAG = . if (CONVSENT_FLAG == -1)
replace UNCONV = . if (UNCONV == -1)
replace UNCONVTRIAL = . if (UNCONVTRIAL == -1)
replace UNCONVTRIAL_FLAG = . if (UNCONVTRIAL_FLAG == -1)
replace UNCONVHOLD = . if (UNCONVHOLD == -1)
replace UNCONVHOLD_FLAG = . if (UNCONVHOLD_FLAG == -1)
replace UNCONVOTHER = . if (UNCONVOTHER == -1)
replace UNCONVOTHER_FLAG = . if (UNCONVOTHER_FLAG == -1)
replace FELONY = . if (FELONY == -1)
replace FELONY_FLAG = . if (FELONY_FLAG == -1)
replace MISD = . if (MISD == -1)
replace MISD_FLAG = . if (MISD_FLAG == -1)
replace OTHEROFF = . if (OTHEROFF == -1)
replace OTHEROFF_FLAG = . if (OTHEROFF_FLAG == -1)
replace TOTOFF = . if (TOTOFF == -1)
replace TOTOFF_FLAG = . if (TOTOFF_FLAG == -1)
replace MARSHALS = . if (MARSHALS == -1)
replace MARSHALS_FLAG = . if (MARSHALS_FLAG == -1)
replace BOP = . if (BOP == -1)
replace BOP_FLAG = . if (BOP_FLAG == -1)
replace ICE = . if (ICE == -1)
replace ICE_FLAG = . if (ICE_FLAG == -1)
replace BIA = . if (BIA == -1)
replace BIA_FLAG = . if (BIA_FLAG == -1)
replace S3Q10A5 = . if (S3Q10A5 == -1)
replace S3Q10A5_FLAG = . if (S3Q10A5_FLAG == -1)
replace INSTATEPRIS = . if (INSTATEPRIS == -1)
replace INSTATEPRIS_FLAG = . if (INSTATEPRIS_FLAG == -1)
replace OUTSTATEPRIS = . if (OUTSTATEPRIS == -1)
replace OUTSTATEPRIS_FLAG = . if (OUTSTATEPRIS_FLAG == -1)
replace TRIBAL = . if (TRIBAL == -1)
replace TRIBAL_FLAG = . if (TRIBAL_FLAG == -1)
replace INSTATEJAIL = . if (INSTATEJAIL == -1)
replace INSTATEJAIL_FLAG = . if (INSTATEJAIL_FLAG == -1)
replace OUTSTATEJAIL = . if (OUTSTATEJAIL == -1)
replace OUTSTATEJAIL_FLAG = . if (OUTSTATEJAIL_FLAG == -1)
replace S3Q10E = . if (S3Q10E == -1)
replace S3Q10E_FLAG = . if (S3Q10E_FLAG == -1)
replace PEAKDATE = . if (PEAKDATE == -1)
replace PEAKPOP = . if (PEAKPOP == -1)
replace PEAKPOP_FLAG = . if (PEAKPOP_FLAG == -1)
replace ADPMALE = . if (ADPMALE == -1)
replace ADPFEMALE = . if (ADPFEMALE == -1)
replace RELEASEMALE = . if (RELEASEMALE == -1)
replace RELEASEMALE_FLAG = . if (RELEASEMALE_FLAG == -1)
replace RELEASEFEMALE = . if (RELEASEFEMALE == -1)
replace RELEASEFEMALE_FLAG = . if (RELEASEFEMALE_FLAG == -1)
replace EMONITOR = . if (EMONITOR == -1)
replace EMONITOR_FLAG = . if (EMONITOR_FLAG == -1)
replace HOMEDETN = . if (HOMEDETN == -1)
replace HOMEDETN_FLAG = . if (HOMEDETN_FLAG == -1)
replace COMMSRV = . if (COMMSRV == -1)
replace COMMSRV_FLAG = . if (COMMSRV_FLAG == -1)
replace DAYREPORT = . if (DAYREPORT == -1)
replace DAYREPORT_FLAG = . if (DAYREPORT_FLAG == -1)
replace PRETRIAL = . if (PRETRIAL == -1)
replace PRETRIAL_FLAG = . if (PRETRIAL_FLAG == -1)
replace ALTWORK = . if (ALTWORK == -1)
replace ALTWORK_FLAG = . if (ALTWORK_FLAG == -1)
replace TREATMENT = . if (TREATMENT == -1)
replace TREATMENT_FLAG = . if (TREATMENT_FLAG == -1)
replace OTRNONCONF = . if (OTRNONCONF == -1)
replace OTRNONCONF_FLAG = . if (OTRNONCONF_FLAG == -1)
replace NONCONFD = . if (NONCONFD == -1)
replace NONCONFD_FLAG = . if (NONCONFD_FLAG == -1)
replace COST = . if (COST == -1)
replace COST_FLAG = . if (COST_FLAG == -1)
replace CORRSTAFF_FLAG = . if (CORRSTAFF_FLAG == -1)
replace TOTALSTAFF_FLAG = . if (TOTALSTAFF_FLAG == -1)
replace CORRWHITE = . if (CORRWHITE == -1)
replace CORRWHITE_FLAG = . if (CORRWHITE_FLAG == -1)
replace CORRBLACK = . if (CORRBLACK == -1)
replace CORRBLACK_FLAG = . if (CORRBLACK_FLAG == -1)
replace CORRHISP = . if (CORRHISP == -1)
replace CORRHISP_FLAG = . if (CORRHISP_FLAG == -1)
replace CORRAIAN = . if (CORRAIAN == -1)
replace CORRAIAN_FLAG = . if (CORRAIAN_FLAG == -1)
replace CORRASIAN = . if (CORRASIAN == -1)
replace CORRASIAN_FLAG = . if (CORRASIAN_FLAG == -1)
replace CORRNHOPI = . if (CORRNHOPI == -1)
replace CORRNHOPI_FLAG = . if (CORRNHOPI_FLAG == -1)
replace CORRTWORACE = . if (CORRTWORACE == -1)
replace CORRTWORACE_FLAG = . if (CORRTWORACE_FLAG == -1)
replace CORROTHERRACE = . if (CORROTHERRACE == -1)
replace CORROTHERRACE_FLAG = . if (CORROTHERRACE_FLAG == -1)
replace CORRRACEDK = . if (CORRRACEDK == -1)
replace CORRRACEDK_FLAG = . if (CORRRACEDK_FLAG == -1)
replace CORRRACETOTAL = . if (CORRRACETOTAL == -1)
replace CORRRACETOTAL_FLAG = . if (CORRRACETOTAL_FLAG == -1)


